<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Servers\Giny.World\Giny.World.csproj" />
  </ItemGroup>

<!--  <Target Name="PostBuild" AfterTargets="PostBuildEvent">-->
<!--    <Exec Condition="'$(IsWindows)'=='true'" Command="copy &quot;$(TargetDir)Giny.DungeonZaap.dll&quot; &quot;$(SolutionDir)Servers\Giny.World\bin\Debug\net8.0\Modules\Giny.DungeonZaap.dll&quot;" />-->
<!--    <Exec Condition="'$(IsWindows)'=='false'" Command="cp &quot;$(TargetDir)Giny.DungeonZaap.dll&quot; &quot;$(SolutionDir)/Servers/Giny.World/bin/Debug/net8.0/Modules/Giny.DungeonZaap.dll&quot;" />-->
<!--  </Target>-->

</Project>
