namespace Giny.World.Managers.Generic;

public enum GenericActionEnum
{
    None,
    Teleport,
    OpenBank,
    RemoveItem,
    LearnOrnament,
    LearnTitle,
    Collect,
    Bidshop,
    Zaap,
    Zaapi,
    CreateGuild,
    LearnSpell,
    AddKamas,
    Craft,
    AddItem,
    AddExperience,
    Notification,
    Fight,
    Smithmagic,
    RuneTrade,
    PokefusWish,
    Unhandled,
    Paddock,
    StartQuest,
    ContinueDialog,
}